export enum SystemState {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  EMERGENCY_STOP = 'EMERGENCY_STOP',
}

export enum PositionState {
  PENDING_ENTRY = 'PENDING_ENTRY',
  PARTIALLY_FILLED = 'PARTIALLY_FILLED',
  OPEN = 'OPEN',
  EXIT_PENDING = 'EXIT_PENDING',
  CLOSED = 'CLOSED',
  FORCE_CLOSED = 'FORCE_CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum LedgerTransactionType {
  FUND = 'FUND',
  RESERVE = 'RESERVE',
  COMMIT_ENTRY = 'COMMIT_ENTRY',
  RELEASE = 'RELEASE',
  REALIZE = 'REALIZE',
  ADJUST = 'ADJUST',
  BROKER_SYNC = 'BROKER_SYNC',
  MTM_UPDATE = 'MTM_UPDATE',
}

export enum TradeStructure {
  LONG_CALL = 'LONG_CALL',
  LONG_PUT = 'LONG_PUT',
  CREDIT_CALL_SPREAD = 'CREDIT_CALL_SPREAD',
  CREDIT_PUT_SPREAD = 'CREDIT_PUT_SPREAD',
}

export enum TradeDirection {
  BULLISH = 'BULLISH',
  BEARISH = 'BEARISH',
  NEUTRAL = 'NEUTRAL',
}

export enum OptionRight {
  C = 'C',
  P = 'P',
}

export enum LegRole {
  SHORT = 'SHORT',
  LONG = 'LONG',
}

export enum GreekSource {
  UW = 'UW',
  MASSIVE = 'MASSIVE',
  MISSING = 'MISSING',
}

export enum LatencyMode {
  CACHED = 'CACHED',
  COLD = 'COLD',
}

export enum FillStatus {
  FILLED = 'FILLED',
  PARTIAL = 'PARTIAL',
  CANCELLED = 'CANCELLED',
  TIMEOUT = 'TIMEOUT',
}

export enum GovernorDecision {
  APPROVE = 'APPROVE',
  RESIZE = 'RESIZE',
  REJECT = 'REJECT',
}

export enum IVRegime {
  LOW = 'LOW',
  NEUTRAL = 'NEUTRAL',
  HIGH = 'HIGH',
  UNKNOWN = 'UNKNOWN',
}

export enum TermShape {
  CONTANGO = 'CONTANGO',
  BACKWARDATION = 'BACKWARDATION',
  FLAT = 'FLAT',
  UNKNOWN = 'UNKNOWN',
}

export enum SnapshotType {
  OPTION_QUOTE = 'OPTION_QUOTE',
  UNDERLYING_PRICE = 'UNDERLYING_PRICE',
  GREEK = 'GREEK',
}

export enum SnapshotSource {
  MASSIVE = 'MASSIVE',
  UW = 'UW',
}

export enum RejectionCode {
  INVALID_INTENT = 'INVALID_INTENT',
  NO_CHAIN_DATA = 'NO_CHAIN_DATA',
  NO_SNAPSHOT_DATA = 'NO_SNAPSHOT_DATA',
  STALE_SNAPSHOT = 'STALE_SNAPSHOT',
  GREEK_SOURCE_UNAVAILABLE = 'GREEK_SOURCE_UNAVAILABLE',
  NO_DELTA = 'NO_DELTA',
  NO_MATCHING_DTE = 'NO_MATCHING_DTE',
  NO_MATCHING_DELTA = 'NO_MATCHING_DELTA',
  LOW_OI = 'LOW_OI',
  LOW_VOLUME = 'LOW_VOLUME',
  WIDE_SPREAD = 'WIDE_SPREAD',
  INVALID_MID_PRICE = 'INVALID_MID_PRICE',
  DATA_SANITY_FAILURE = 'DATA_SANITY_FAILURE',
  GAMMA_SIGN_SANITY_FAILURE = 'GAMMA_SIGN_SANITY_FAILURE',
  UNDERLYING_PRICE_SANITY_FAILURE = 'UNDERLYING_PRICE_SANITY_FAILURE',
  LOW_LIQUIDITY_SCORE = 'LOW_LIQUIDITY_SCORE',
  INSUFFICIENT_CANDIDATES = 'INSUFFICIENT_CANDIDATES',
  BAD_SPREAD_CREDIT = 'BAD_SPREAD_CREDIT',
  RISK_TOO_HIGH = 'RISK_TOO_HIGH',
  LATENCY_BUDGET_EXCEEDED = 'LATENCY_BUDGET_EXCEEDED',
  SYSTEM_NOT_ACTIVE = 'SYSTEM_NOT_ACTIVE',
  LEDGER_LOCK_TIMEOUT = 'LEDGER_LOCK_TIMEOUT',
  POSITION_WRITE_CONFLICT = 'POSITION_WRITE_CONFLICT',
  UNKNOWN_IV_REGIME = 'UNKNOWN_IV_REGIME',
  UNDERLYING_ILLIQUID = 'UNDERLYING_ILLIQUID',
  QUOTE_INSTABILITY = 'QUOTE_INSTABILITY',
  STALE_QUOTE_AT_SUBMISSION = 'STALE_QUOTE_AT_SUBMISSION',
  FILL_TIMEOUT = 'FILL_TIMEOUT',
  UNDERLYING_MOVED_DURING_REPRICE = 'UNDERLYING_MOVED_DURING_REPRICE',
  INSUFFICIENT_CAPITAL = 'INSUFFICIENT_CAPITAL',
  ANALYTICS_UNAVAILABLE = 'ANALYTICS_UNAVAILABLE',
  SESSION_CLOSED = 'SESSION_CLOSED',
  PSYCHOLOGICAL_PAUSE = 'PSYCHOLOGICAL_PAUSE',
  BUCKET_EXHAUSTED = 'BUCKET_EXHAUSTED',
}

export enum SystemStateTransitionTrigger {
  MANUAL = 'MANUAL',
  BROKER_SYNC_FREEZE = 'BROKER_SYNC_FREEZE',
  STREAM_DISCONNECT = 'STREAM_DISCONNECT',
  LEDGER_WRITE_FAILURE = 'LEDGER_WRITE_FAILURE',
  DOUBLE_RESERVATION = 'DOUBLE_RESERVATION',
  RECONCILIATION_FAILURE = 'RECONCILIATION_FAILURE',
  STARTUP = 'STARTUP',
}
